version: "2.1"
services:

    ###############################################################################################################
    ################################################## Databases ##################################################
    ###############################################################################################################
    # Postgres
    postgres:
        image: postgres:11
        container_name: PostgreSQL
        restart: always
        environment:
            - POSTGRES_USER=sample
            - POSTGRES_PASSWORD=sample123456789
            - POSTGRES_DB=sample
        ports:
            - "5400:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data 
            - ./postgres/scripts/init.sh /docker-entrypoint-initdb.d/
        networks:
            - sample
    
    # Redis
    redis:
        image: 'bitnami/redis:latest'
        container_name: Redis
        environment:
            - REDIS_PASSWORD=sample123456789
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/bitnami/redis
        networks:
            - sample

# sample virtual network
networks:
    sample:
        name: sample
        driver: bridge
