routing:

  # ******** Auth ********
  - name: login
    controller: auth/login
    path: /login
    method: POST
    token: optional

  - name: register
    controller: auth/register
    path: /register
    method: POST
    token: optional

  - name: logout
    controller: auth/logout
    path: /logout
    method: POST
    token: optional

  - name: auth
    controller: auth/getAll
    path: /auth
    method: GET
    token: optional

# ******** User ********
  - name: me
    controller: user/me
    path: /me
    method: GET
    token: required